
const classRaceLookup = {
  "Animist": {
    "Amphibians": "yes",
    "Beastmen": "yes",
    "Birdfolk": "",
    "Catfolk": "yes",
    "Celestials": "",
    "Centaurs": "yes",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "yes",
    "Elves": "yes",
    "Goblins": "yes",
    "Halfling": "yes",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "yes",
    "Orcs": "yes",
    "Ratfolk": "yes",
    "Renegade Dwarves": "",
    "Reptilians": "yes",
    "Shardminds": "yes",
    "Treefolk": "yes",
    "Trolls": "",
    "Vampires": ""
  },
  "Assassin": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "yes",
    "Catfolk": "yes",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "yes",
    "Humans": "",
    "Infernals": "yes",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "yes",
    "Renegade Dwarves": "yes",
    "Reptilians": "yes",
    "Shardminds": "yes",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Barbarian": {
    "Amphibians": "",
    "Beastmen": "yes",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "yes",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "yes",
    "Ogres": "yes",
    "Orcs": "yes",
    "Ratfolk": "",
    "Renegade Dwarves": "yes",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Bard": {
    "Amphibians": "",
    "Beastmen": "yes",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "yes",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "",
    "Elves": "yes",
    "Goblins": "",
    "Halfling": "yes",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "yes",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Battle dancer": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "yes",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Forester": {
    "Amphibians": "",
    "Beastmen": "yes",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "yes",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Gladiator": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "",
    "Elves": "yes",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "yes",
    "Orcs": "yes",
    "Ratfolk": "",
    "Renegade Dwarves": "yes",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Knight": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "no",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": "yes"
  },
  "Necromancer": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "no",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": "yes"
  },
  "Paladin": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "yes",
    "Centaurs": "yes",
    "Cyclops": "no",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "yes",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "yes",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Ranger": {
    "Amphibians": "yes",
    "Beastmen": "yes",
    "Birdfolk": "",
    "Catfolk": "yes",
    "Celestials": "",
    "Centaurs": "yes",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "yes",
    "Dogfolk": "yes",
    "Elves": "yes",
    "Goblins": "",
    "Halfling": "yes",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "no spells",
    "Orcs": "no spells",
    "Ratfolk": "",
    "Renegade Dwarves": "yes",
    "Reptilians": "yes",
    "Shardminds": "",
    "Treefolk": "yes",
    "Trolls": "",
    "Vampires": ""
  },
  "Rogue": {
    "Amphibians": "",
    "Beastmen": "yes",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "yes",
    "Halfling": "yes",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "yes",
    "Renegade Dwarves": "yes",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Runic Master": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "yes",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "yes",
    "Reptilians": "",
    "Shardminds": "yes",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Scout": {
    "Amphibians": "yes",
    "Beastmen": "yes",
    "Birdfolk": "yes",
    "Catfolk": "yes",
    "Celestials": "yes",
    "Centaurs": "yes",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "yes",
    "Elves": "yes",
    "Goblins": "yes",
    "Halfling": "yes",
    "Humans": "yes",
    "Infernals": "yes",
    "Minotaurs": "",
    "Ogres": "yes",
    "Orcs": "yes",
    "Ratfolk": "yes",
    "Renegade Dwarves": "yes",
    "Reptilians": "yes",
    "Shardminds": "yes",
    "Treefolk": "yes",
    "Trolls": "yes",
    "Vampires": ""
  },
  "Sorcerer": {
    "Amphibians": "Tribal only",
    "Beastmen": "Tribal only",
    "Birdfolk": "yes",
    "Catfolk": "Tribal only",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "Tribal only",
    "Elves": "",
    "Goblins": "yes",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "Tribal only",
    "Orcs": "Tribal only",
    "Ratfolk": "yes",
    "Renegade Dwarves": "yes",
    "Reptilians": "Tribal only",
    "Shardminds": "yes",
    "Treefolk": "",
    "Trolls": "Tribal only",
    "Vampires": "Witchcraft only"
  },
  "Underworld Sorcerer": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Warrior": {
    "Amphibians": "yes",
    "Beastmen": "yes",
    "Birdfolk": "yes",
    "Catfolk": "yes",
    "Celestials": "yes",
    "Centaurs": "yes",
    "Cyclops": "yes",
    "Dark Elves": "yes",
    "Dwarves": "yes",
    "Dogfolk": "yes",
    "Elves": "yes",
    "Goblins": "yes",
    "Halfling": "yes",
    "Humans": "yes",
    "Infernals": "yes",
    "Minotaurs": "yes",
    "Ogres": "yes",
    "Orcs": "yes",
    "Ratfolk": "yes",
    "Renegade Dwarves": "yes",
    "Reptilians": "yes",
    "Shardminds": "yes",
    "Treefolk": "yes",
    "Trolls": "yes",
    "Vampires": "yes"
  },
  "Warrior Monk": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "yes",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Witch Hunter": {
    "Amphibians": "",
    "Beastmen": "",
    "Birdfolk": "",
    "Catfolk": "",
    "Celestials": "",
    "Centaurs": "",
    "Cyclops": "no",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "",
    "Ratfolk": "",
    "Renegade Dwarves": "",
    "Reptilians": "",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  },
  "Wizard": {
    "Amphibians": "Not Corruption or Underworld",
    "Beastmen": "",
    "Birdfolk": "yes",
    "Catfolk": "",
    "Celestials": "yes",
    "Centaurs": "",
    "Cyclops": "yes",
    "Dark Elves": "",
    "Dwarves": "",
    "Dogfolk": "",
    "Elves": "Not Corruption or Underworld",
    "Goblins": "",
    "Halfling": "",
    "Humans": "yes",
    "Infernals": "",
    "Minotaurs": "",
    "Ogres": "",
    "Orcs": "Fire or Corruption only",
    "Ratfolk": "",
    "Renegade Dwarves": "Not Corruption or Underworld",
    "Reptilians": "yes",
    "Shardminds": "",
    "Treefolk": "",
    "Trolls": "",
    "Vampires": ""
  }
};
