
const races = [
  {
    name: "Amphibians",
    mov: { min: 4, max: 5, cost: 1 },
    combat: { min: 3, max: 4, cost: 2 },
    strength: { min: 2, max: 3, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 7,
    agility: { min: 4, max: 5, cost: 2 },
    intelligence: { min: 2, max: 5, cost: 1 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 4, cost: 1 },
    vitality: { min: 3, max: 5, cost: 2 },
    notes: "Small sneaky and stealthy. They begin with the skills still and small and Pathfinder open 4 in Forest flooded area swamp)"
  },
  {
    name: "Beastmen",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 3 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 2, max: 4, cost: 2 },
    armor: 3,
    fortune: 4,
    agility: { min: 3, max: 4, cost: 2 },
    intelligence: { min: 3, max: 4, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 4, max: 7, cost: 1 },
    notes: "Strong tough Hardy not to school for with weapons. They begin with the skill onslaught"
  },
  {
    name: "Birdfolk",
    mov: { min: 5, max: 6, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 2 },
    shooting: { min: 2, max: 4, cost: 2 },
    armor: 3,
    fortune: 6,
    agility: { min: 3, max: 4, cost: 2 },
    intelligence: { min: 3, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 6, cost: 2 },
    notes: "Begins with skills flying 10 and Eagle Eye"
  },
  {
    name: "Catfolk",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 5, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 4,
    agility: { min: 4, max: 5, cost: 2 },
    intelligence: { min: 3, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 6, cost: 2 },
    notes: "Outstanding agility and very high potential strength"
  },
  {
    name: "Celestials",
    mov: { min: 5, max: 6, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 3,
    agility: { min: 3, max: 5, cost: 2 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 2, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 6, cost: 2 },
    notes: "they look like humans however the blood of the Gods runs through their veins. They begin with the skill invulnerable. They may learn the skill fly 8. They can never reach Armor value of 6"
  },
  {
    name: "Centaurs",
    mov: { min: 7, max: 8, cost: 2 },
    combat: { min: 3, max: 4, cost: 3 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 3, max: 4, cost: 2 },
    armor: 3,
    fortune: 4,
    agility: { min: 3, max: 4, cost: 2 },
    intelligence: { min: 3, max: 4, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 5, max: 8, cost: 1 },
    notes: "Fast and tough. They began with the skill Onslaught + 2 Agility (wing) tests will jumping. 02 wheel climbing. Can't use heavy armor"
  },
  {
    name: "Cyclops",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 3 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 2, max: 4, cost: 2 },
    armor: 3,
    fortune: 6,
    agility: { min: 2, max: 4, cost: 2 },
    intelligence: { min: 2, max: 4, cost: 1 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 5, max: 8, cost: 1 },
    notes: "Brave strong temperamental that begin with the skill onslaught"
  },
  {
    name: "Dark Elves",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 3 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 4,
    agility: { min: 4, max: 5, cost: 2 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 5, cost: 3 },
    notes: "Add standing agility and speed. Skillful with weapons. It beginning with the skills sharp senses and cruel"
  },
  {
    name: "Dogfolk",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 3 },
    strength: { min: 3, max: 4, cost: 1 },
    shooting: { min: 3, max: 4, cost: 2 },
    armor: 3,
    fortune: 5,
    agility: { min: 3, max: 4, cost: 2 },
    intelligence: { min: 3, max: 5, cost: 1 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 5, max: 6, cost: 2 },
    notes: "Not Very skillful with weapons. They have a good sense of smell and strong though. Starting skills are sharp senses and tracker. May use the weapon fangs"
  },
  {
    name: "Dwarves",
    mov: { min: 4, max: 5, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 5,
    agility: { min: 2, max: 3, cost: 1 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 5, max: 7, cost: 2 },
    notes: "Slow but loyal. Brave and very tough. They began with the skill 'tough'. hatred towards orks and goblins and skilled hands"
  },
  {
    name: "Elves",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 3 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 5,
    agility: { min: 4, max: 5, cost: 2 },
    intelligence: { min: 4, max: 5, cost: 1 },
    mana: { min: 0, max: 2, cost: 1 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 5, cost: 3 },
    notes: "outstanding agility and speed. Scoville with both melee and ranged weapons. Great potential as spell casters. They begin with the skills sharp senses"
  },
  {
    name: "Goblin",
    mov: { min: 4, max: 5, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 2, max: 4, cost: 2 },
    shooting: { min: 3, max: 4, cost: 2 },
    armor: 3,
    fortune: 7,
    agility: { min: 4, max: 5, cost: 2 },
    intelligence: { min: 3, max: 4, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 2, max: 4, cost: 1 },
    vitality: { min: 3, max: 4, cost: 2 },
    notes: "Small though expert and dirty fighting. They begin with the skills small stealth and dirty fighter"
  },
  {
    name: "Halflings",
    mov: { min: 4, max: 5, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 2, max: 3, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 8,
    agility: { min: 3, max: 5, cost: 1 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 3, max: 4, cost: 3 },
    notes: "Small though Lucky. They begin with the skills small lost in the dark and stealth"
  },
  {
    name: "Humans",
    mov: { min: 5, max: 6, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 6,
    agility: { min: 3, max: 5, cost: 2 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 6, cost: 2 },
    notes: "Begins with the skill 'in the dark' and one more skill at the players choise depending on the class chosen. They may learn the skill lycantrhopy, but then loose 2 fortune points."
  },
  {
    name: "Infernals",
    mov: { min: 5, max: 6, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 2, max: 4, cost: 2 },
    armor: 3,
    fortune: 2,
    agility: { min: 2, max: 5, cost: 1 },
    intelligence: { min: 3, max: 4, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 4, max: 7, cost: 1 },
    notes: "Lethal and very tough. They begin with the skills: invulnerable underworld and fearsome. They may learn skill flying 8. Can't wear heavy armor. Can use weapon claws"
  },
  {
    name: "Minotaurs",
    mov: { min: 6, max: 7, cost: 2 },
    combat: { min: 3, max: 4, cost: 3 },
    strength: { min: 6, max: 8, cost: 1 },
    shooting: { min: 1, max: 2, cost: 2 },
    armor: 3,
    fortune: 2,
    agility: { min: 2, max: 3, cost: 1 },
    intelligence: { min: 2, max: 3, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 8, max: 14, cost: 1 },
    notes: "Huge and uncontrollable. It began with the skills large fearsome Onslaught and clumsy hands and preserver. They can't wear heavy armor. Can use the weapon horns"
  },
  {
    name: "Ogres",
    mov: { min: 6, max: 7, cost: 2 },
    combat: { min: 3, max: 4, cost: 3 },
    strength: { min: 6, max: 8, cost: 2 },
    shooting: { min: 2, max: 4, cost: 2 },
    armor: 3,
    fortune: 2,
    agility: { min: 2, max: 3, cost: 1 },
    intelligence: { min: 3, max: 4, cost: 3 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 8, max: 12, cost: 1 },
    notes: "Mighty Warriors. They are more versatile than the other creatures with a similar size. They begin with the skills large fearsome and Onslaught. They can it reach a Armour value of 6"
  },
  {
    name: "Orcs",
    mov: { min: 5, max: 6, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 2, max: 4, cost: 2 },
    armor: 3,
    fortune: 6,
    agility: { min: 2, max: 4, cost: 2 },
    intelligence: { min: 3, max: 4, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 7, cost: 1 },
    notes: "Begins with the skills clumsy hands and brutal"
  },
  {
    name: "Ratfolk",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 3 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 7,
    agility: { min: 4, max: 5, cost: 2 },
    intelligence: { min: 3, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 4, cost: 1 },
    vitality: { min: 3, max: 5, cost: 2 },
    notes: "Begins with the skills slippery"
  },
  {
    name: "Renegade Dwarves",
    mov: { min: 4, max: 5, cost: 2 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 4, cost: 2 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 4,
    agility: { min: 2, max: 3, cost: 1 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 5, max: 7, cost: 2 },
    notes: "Slow dexterous Brave and very tough. They begin with the skills tough cruel and skilled hands"
  },
  {
    name: "Reptilians",
    mov: { min: 5, max: 6, cost: 3 },
    combat: { min: 3, max: 5, cost: 3 },
    strength: { min: 3, max: 5, cost: 2 },
    shooting: { min: 3, max: 4, cost: 2 },
    armor: 4,
    fortune: 5,
    agility: { min: 2, max: 4, cost: 2 },
    intelligence: { min: 2, max: 4, cost: 1 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 3, max: 5, cost: 1 },
    vitality: { min: 4, max: 7, cost: 2 },
    notes: "Tough and Hardy but slow. Begins with the skill cold blood and Pathfinder (flooded areas , swamp) they can use the weapon claws"
  },
  {
    name: "Shardminds",
    mov: { min: 5, max: 6, cost: 2 },
    combat: { min: 3, max: 5, cost: 3 },
    strength: { min: 3, max: 4, cost: 2 },
    shooting: { min: 3, max: 5, cost: 3 },
    armor: 3,
    fortune: 6,
    agility: { min: 2, max: 4, cost: 1 },
    intelligence: { min: 4, max: 5, cost: 1 },
    mana: { min: 0, max: 2, cost: 1 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 3, max: 5, cost: 2 },
    notes: "Extraordinary beings with brittle bodies. Immune to poisons diseases and offensive spells that cause damage Against Natural Armor. All Critical Hits they receive ignore old benefits of the armor they wear"
  },
  {
    name: "Treefolk",
    mov: { min: 4, max: 5, cost: 2 },
    combat: { min: 3, max: 4, cost: 3 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 2, max: 3, cost: 3 },
    armor: 5,
    fortune: 4,
    agility: { min: 1, max: 3, cost: 2 },
    intelligence: { min: 2, max: 4, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 4, max: 7, cost: 1 },
    notes: "Begins with the skills vulnerable to fire survive. Can't wear any armor. Can use the weapon claws"
  },
  {
    name: "Trolls",
    mov: { min: 6, max: 7, cost: 3 },
    combat: { min: 2, max: 4, cost: 2 },
    strength: { min: 7, max: 9, cost: 2 },
    shooting: { min: 3, max: 2, cost: 3 },
    armor: 4,
    fortune: 2,
    agility: { min: 1, max: 2, cost: 2 },
    intelligence: { min: 2, max: 3, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 8, max: 14, cost: 1 },
    notes: "Begins with the skills large fearsome sweep regeneration stupid and vulnerable to fire. They may learn corrosive vomit. Can't wear heavy armor."
  },
  {
    name: "Vampires",
    mov: { min: 5, max: 6, cost: 1 },
    combat: { min: 3, max: 5, cost: 2 },
    strength: { min: 3, max: 5, cost: 1 },
    shooting: { min: 3, max: 5, cost: 2 },
    armor: 3,
    fortune: 2,
    agility: { min: 3, max: 5, cost: 1 },
    intelligence: { min: 4, max: 5, cost: 2 },
    mana: { min: 0, max: 0, cost: 0 },
    courage: { min: 4, max: 5, cost: 1 },
    vitality: { min: 4, max: 6, cost: 2 },
    notes: "Begins with 2 skills Leach Vitality only while using fangs sharp senses and regeneration. May learn skill flying and fearsome. They can never reach the armor value of 6. They lose their natural skills under daylight. Can use the weapon fangs"
  }
];
